stages:
- name: helm3-nginx
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:xiq-chart-nginx-static
      version: 3.1.0
      name: nginx-static
      targetNamespace: default
notification: {}
